allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
buildscript {
    repositories {
        google() // Ensure this is included
        mavenCentral()// Optional, depending on your project
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3' // Your Gradle plugin version
        classpath 'com.google.gms:google-services:4.4.2' // Make sure this line is correct
    }
}



rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
